services:
  - type: web
    name: sorcerer2-leaderboard
    runtime: node
    rootDir: leaderboard-api
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
